<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'DifferentialGhcTracField' => 'extensions/differential/customfield/DifferentialGhcTracField.php',
    'PhabricatorBotGhcTracHandler' => 'extensions/bot/handler/PhabricatorBotGhcTracHandler.php',
    'PhabricatorBotMiscGhcHandler' => 'extensions/bot/handler/PhabricatorBotMiscGhcHandler.php',
    'PhabricatorBotServerAdminLogHandler' => 'extensions/bot/handler/PhabricatorBotServerAdminLogHandler.php',
    'PhabricatorRemarkupGhcTracRule' => 'extensions/markup/engine/remarkup/markuprule/PhabricatorRemarkupGhcTracRule.php',
    'SetTaskEditPolicyHeraldCustomAction' => 'extensions/herald/customaction/SetTaskEditPolicyHeraldCustomAction.php',
    'SetTaskViewPolicyHeraldCustomAction' => 'extensions/herald/customaction/SetTaskViewPolicyHeraldCustomAction.php',
  ),
  'function' => array(),
  'xmap' => array(
    'DifferentialGhcTracField' => 'DifferentialStoredCustomField',
    'PhabricatorBotGhcTracHandler' => 'PhabricatorBotHandler',
    'PhabricatorBotMiscGhcHandler' => 'PhabricatorBotHandler',
    'PhabricatorBotServerAdminLogHandler' => 'PhabricatorBotHandler',
    'PhabricatorRemarkupGhcTracRule' => 'PhabricatorRemarkupCustomInlineRule',
    'SetTaskEditPolicyHeraldCustomAction' => 'HeraldCustomAction',
    'SetTaskViewPolicyHeraldCustomAction' => 'HeraldCustomAction',
  ),
));
